name: GitHub Actions Test
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"


jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Run in all these versions of Python
        python-version: [3.9]

    steps:
      # Checkout the latest code from the repo
      - name: Checkout repo
        uses: actions/checkout@v2
        # Setup which version of Python to use
      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Fetch Dataset

        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_TOKEN: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          mkdir -p .dvc/tmp
          touch .dvc/tmp/gdrive-user-credentials.json
          echo $GDRIVE_TOKEN > .dvc/tmp/gdrive-user-credentials.json
          dvc pull -r myremote 
      - name: Run tests
        run: python -m unittest tests/test_loadData.py
      